FORMAT: 1A
HOST: http://Localhost:3000

# dotiful

Convert torrent file to magnet URI.

## Magnet Collection [/magnet]

### Get magnet URI [POST]

+ Request (application/json)

        {
            "url": "https://mac-torrents.io/wp-content/uploads/2019/06/Visual-Studio-Code-1.35.1.zip.torrent"
        }

+ Response 200
    
    + Headers

            Content-Type:application/json; charset=utf-8

    + Body

            {
                "uri":"magnet:?xt=urn:btih:2d82f15770ee5376f6cfedce9a05fd6b8aa11d79&dn=Visual+Studio+Code+1.35.1.zip&tr=http%3A%2F%2F182.176.139.129%3A6969%2Fannounce&tr=http%3A%2F%2F91.218.230.81%3A6969%2Fannounce&tr=http%3A%2F%2Fatrack.pow7.com%2Fannounce&tr=http%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.appdn.net%3A2710%2Fannounce"
            }
